# dataset config : Sequential Recommendation
dataset_save_path: /path/to/data

USER_ID_FIELD: user_id
ITEM_ID_FIELD: app_package
TIME_FIELD: unix_timestamp
device: gpu
load_col:
    inter: [user_id, app_package, unix_timestamp, time_diff_in_days]
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
neg_sampling:
# Training and evaluation config
epochs: 100
time_diff_pos_emb: 641
loss_type: CE
train_batch_size: 4096
eval_batch_size: 4096
train_neg_sample_args: ~
    
checkpoint_dir: ./checkpoints
log_dir: ./InterPosGatedFusion-scaled_rhythm-0point2-Action-5core/
log_tensorboard: ./InterPosGatedFusion-scaled_rhythm-0point2-Action-5core/


logging_steps: 10
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full
metrics: ['MRR', 'NDCG', 'Hit']
topk: [5, 10, 15, 20, 30, 50]
valid_metric: MRR@10
